services:
  nuxt-app:
    image: nuxt-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NUXT_DATABASE_URL=postgresql://postgres:postgres@pc1.lan:5432/testdb
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s